[project]
name = "barometro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Gabriel Rodrigues", email = "rodriguesgasoares@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.5",
    "pytest>=9.1.1",
    "requests>=2.34.2",
    "ruff>=0.16.7",
]

[project.scripts]
barometro = "barometro:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
